server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    enabled: true # swagger on/off
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/testdb?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mysql.jdbc.Driver
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace
