name: matZip-v3

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        env:
          SPRING_PROFILES_ACTIVE: test
          PORTONE_API_KEY: ${{ secrets.PORTONE_API_KEY }}
          PORTONE_API_SECRET_KEY: ${{ secrets.PORTONE_API_SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
        run: ./gradlew clean build

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build for Deployment
        env:
          SPRING_PROFILES_ACTIVE: prod
          PORTONE_API_KEY: ${{ secrets.PORTONE_API_KEY }}
          PORTONE_API_SECRET_KEY: ${{ secrets.PORTONE_API_SECRET_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
          FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}
        run: ./gradlew clean build

      # UTC가 기준이기 때문에 한국시간으로 맞추려면 +9시간 해야 한다
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time #current-time 이란 변수에 시간이 담긴다.
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

      - name: Check if jar file exists # jar 파일 존재 확인(로그)
        run: ls -al build/libs

      - name: Create Procfile and .ebextensions
        run: |
          echo "web: /sbin/appstart" > Procfile
          mkdir -p .ebextensions
          echo "files:\n    \"/sbin/appstart\":\n        mode: \"000755\"\n        owner: webapp\n        group: webapp\n        content: |\n            #!/usr/bin/env bash\n            JAR_PATH=/var/app/current/application.jar\n\n            # run app\n            java -Dspring.profiles.active=prod -Dfile.encoding=UTF-8 -jar $JAR_PATH\n\ncontainer_commands:\n    01_start_application:\n        command: \"/sbin/appstart\"" > .ebextensions/00-makefile.config

      - name: Generate deployment package
        run: |
          mkdir -p deploy
          cp build/libs/MAT_ZIP_migration-0.0.1-SNAPSHOT.jar deploy/application.jar
          cp Procfile deploy/Procfile
          cp -r .ebextensions deploy/.ebextensions
          cd deploy && zip -r deploy.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }} #IAM 액세스키
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }} #IAM 시크릿키
          application_name: matZip-v3 #엘라스틱빈스톡 애플리케이션 이름
          environment_name: MatZip-v3 #엘라스틱빈스톡 환경 이름
          version_label: matZip-v3-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy/deploy.zip
